### ISSUE TITLE
ReferenceError: Can't find variable: A0Lock — auth0.js:14

### ISSUE THREAD

**Issue by chrishawn** [sitefinitysteve/nativescript-auth0#13]
when i try to use this the console dumps 
`ReferenceError: Can't find variable: A0Lock — auth0.js:14`
after i do this.lock.show()

**Comment by arpit2438735** [comment]
same issue I am also facing

**Comment by arpit2438735** [comment]
@chrishawn I got the issue it because of new version of Lock getting added inside PodFile and they changed the function name inside it.I send the pull request #18 related to that change

**Comment by sitefinitysteve** [comment]
Please try again with latest package
