### ISSUE TITLE
Getting error when integrate with current nativescript application

### ISSUE THREAD

**Issue by arpit2438735** [sitefinitysteve/nativescript-auth0#15]
Hi,

I am getting error when I do `tns run ios --emulator`.Below are the error
                                     ^
/Users/nativescript/platforms/ios/Pods/Auth0/Auth0/WebAuth.swift:175:38: error: consecutive declarations on a line must be separated by ';'
    @available(*, deprecated, message: "use response([.token])")
                                     ^
                                     ;
/Users/nativescript/platforms/ios/Pods/Auth0/Auth0/WebAuth.swift:175:38: error: expected declaration
    @available(*, deprecated, message: "use response([.token])")
                                     ^
/Users/netwarmer/nativescript/platforms/ios/Pods/Auth0/Auth0/WebAuth.swift:202:29: error: unknown attribute 'escaping'
    func start(_ callback: @escaping (Result<Credentials>) -> Void)
                            ^
/Users/nativescript/platforms/ios/Pods/Auth0/Auth0/Auth0Error.swift:33:29: error: use of undeclared type 'Error'
public protocol Auth0Error: Error {
                            ^~~~~
/Users/nativescript/platforms/ios/Pods/Auth0/Auth0/NSData+URLSafe.swift:25:18: error: use of undeclared type 'Data'
public extension Data {
                 ^~~~
/Users/nativescript/platforms/ios/Pods/Auth0/Auth0/NSURL+Auth0.swift:25:18: error: use of undeclared type 'URL'
public extension URL {
                 ^~~
/Users/nativescript/platforms/ios/Pods/Auth0/Auth0/NSURLComponents+OAuth2.swift:25:11: error: use of undeclared type 'URLComponents'
extension URLComponents {
          ^~~~~~~~~~~~~
/Users/nativescript/platforms/ios/Pods/Auth0/Auth0/AuthenticationError.swift:147:32: error: use of undeclared type 'CustomNSError'
extension AuthenticationError: CustomNSError {
                               ^~~~~~~~~~~~~

** BUILD FAILED **

The following build commands failed:
	CompileSwift normal x86_64 /Users/nativescript/platforms/ios/Pods/Auth0/Auth0/_ObjectiveAuthenticationAPI.swift
	CompileSwift normal x86_64 /Users/nativescript/platforms/ios/Pods/Auth0/Auth0/_ObjectiveManagementAPI.swift
	CompileSwift normal x86_64 /Users/nativescript/platforms/ios/Pods/Auth0/Auth0/_ObjectiveWebAuth.swift
	CompileSwift normal x86_64 
/Users/nativescript/platforms/ios/Pods/Auth0/Auth0/Auth0.swift
	CompileSwift normal x86_64 /Users/nativescript/platforms/ios/Pods/Auth0/Auth0/Auth0Authentication.swift
	CompileSwift normal x86_64 /Users/nativescript/platforms/ios/Pods/Auth0/Auth0/Auth0Error.swift
	CompileSwift normal x86_64 /Users/nativescript/platforms/ios/Pods/Auth0/Auth0/Authentication.swift
	CompileSwift normal x86_64 /Users/nativescript/platforms/ios/Pods/Auth0/Auth0/AuthenticationError.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler

**Comment by sitefinitysteve** [comment]
Okay I’ll check it out, v3 was released today so I need to re-open it all anyway

**Comment by arpit2438735** [comment]
Thanks for your reply.How can I go back to previous version or is this the problem with newer version?

**Comment by sitefinitysteve** [comment]
Not moving this into v3 yet, thx for the PR, updated a couple other things in the podspec as well
