### ISSUE TITLE
Lock (~> 2.0) required by Podfile

### ISSUE THREAD

**Issue by budilovskiy** [sitefinitysteve/nativescript-auth0#16]
Hi.
I have got an error when trying to run demo project on iOS:

> [!] Unable to satisfy the following requirements:
`Lock (~> 2.0)` required by `Podfile`
Specs satisfying the `Lock (~> 2.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by arpit2438735** [comment]
I also faced the same issue.For now if you want to continue just add `platform :ios, '9.0'` inside `PodFile` under `platform/ios` folder.

The problem is that your Pod doesn't know the version of iOS

**Comment by sitefinitysteve** [comment]
Can you update the npm package and try again?

**Comment by budilovskiy** [comment]
It works. Thank you
