### ISSUE TITLE
Demo app is not working on iOS

### ISSUE THREAD

**Issue by budilovskiy** [sitefinitysteve/nativescript-auth0#17]
Hi. When I'm trying to run the Demo app on iOS I get this error:
`file:///app/login.js:22:20: ReferenceError: Can't find variable: A0Lock`.
Steps to reproduce:
1. Add `platform :ios, '9.0'` to .../nativescript-auth0-master/demo/platforms/ios/Podfile
2. Delete `"nativescript-auth0": "file:..",` in package.json line 12:
3. `tns plugin add nativescript-auth0`
4. `tns run ios`

Simulator device: iPhone 6 iOS 10.3
TypeScript 2.3.2

**Comment by arpit2438735** [comment]
It' because of new version of Lock.Here's the fix #18 ,waiting for merge.

**Comment by sitefinitysteve** [comment]
Can you update the npm package and try again?

**Comment by budilovskiy** [comment]
Yes, now Lock is working as expected. But I have a callback handling problem after login:
> Callback URL mismatch.
The url "org.nativescript.auth0demo://nativescript.auth0.com/ios/org.nativescript.auth0demo/callback" is not in the list of allowed callback URLs: https://nativescript.auth0.com/android/org.nativescript.auth0demo/callback.
Please go to the Application Settings page and make sure you are sending a valid callback url from your application.

**Comment by arpit2438735** [comment]
Yes same issue I am also facing.Let me look and debug the issue.It could be because of this 
https://auth0.com/forum/t/the-url-is-not-in-the-list-of-callback-urls/4264/8

**Comment by sitefinitysteve** [comment]
Yeah, that's just a config issue on the auth0 side, was late didn't update
it sorry.  Clearly you would use your own in your app.

**Comment by budilovskiy** [comment]
I was trying to run my app on iOS after configuring Allowed Callback URLs on the auth0 Client's Dashboard. But now I have the problem with returning to my app after login.
For example I have defined nativescript.id in package.json:
`"nativescript": {`
`    "id": "org.nativescript.nativeScript",`
`    "tns-ios": {`
`      "version": "3.0.0"`
`    }`
`  },`

My Allowed Callback URLs contains this string:
org.nativescript.nativeScript://{My_Client_Domain}/ios/org.nativescript.nativeScript/callback

Then I have add this to my Auth0.plist:
`<key>ClientId</key>`
`    <string>{My_Client_ID}</string>`
 `   <key>Domain</key>`
`    <string>{My_Client_Domain}</string>`

And finally I have defined URL scheme in Info.plist:
`<key>CFBundleURLTypes</key>`
`	<array>`
`		<dict>`
`			<key>CFBundleTypeRole</key>`
`			<string>None</string>`
`			<key>CFBundleURLName</key>`
`			<string>auth0</string>`
`			<key>CFBundleURLSchemes</key>`
`			<array>`
`				<string>org.nativescript.nativeScript</string>`
`			</array>`
`		</dict>`
`	</array>`

But after login callback from Auth0 handled in Safari, not in my app.
I think my problem is in CFBundleURLSchemes section of Info.plist. What string I must paste in it? According to this: [https://auth0.com/docs/quickstart/native/ios-swift#configure-callback-urls](url) there must be a PRODUCT_BUNDLE_IDENTIFIER.
Could you please clarify how to setup it on iOS.

**Comment by arpit2438735** [comment]
Did you try add this
```<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>None</string>
        <key>CFBundleURLName</key>
        <string>auth0</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>// Replace key with this value
        </array>
    </dict>
</array>

**Comment by budilovskiy** [comment]
I try to replace key with `<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>` and now I get message from Safari:
> Safari cannot open the page because the address is invalid.

**Comment by sitefinitysteve** [comment]
Yeah I'm working this out now, even if you did get it solved the api has
slightly​ changed, hang tight

On May 10, 2017 12:58 PM, "Maksim Budilovskiy" <notifications@github.com>
wrote:

I try to replace key with <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string> and
now I get message from Safari:

Safari cannot open the page because the address is invalid.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sitefinitysteve/nativescript-auth0/issues/17#issuecomment-300546395>,
or mute the thread

**Comment by sitefinitysteve** [comment]
Okay latest version checked in, so we need to now implement a couple Delegate callbacks https://github.com/sitefinitysteve/nativescript-auth0#impliement-delegate

...but the demo now properly returns the tokens and closes the lock

I have an open issue with the ios runtime guys to see how we can impliment the .withOptions and .style properties https://github.com/NativeScript/ios-runtime/issues/257#issuecomment-300582232

**Comment by budilovskiy** [comment]
I have tested new version of Demo app with plugin v1.2.0
It is working on iOS and returns to the app after login, but I've got a runtime exception on Android:

> ReferenceError: UIResponder is not defined
File: "file:///data/data/org.nativescript.auth0demo/files/app/custom-app-delegate.js, line: 58, column: 2
StackTrace:
 	Frame: function:'', file:'file:///data/data/org.nativescript.auth0demo/files/app/custom-app-delegate.js', line: 58, column: 3
 	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.auth0demo/files/app/app.js', line: 4, column: 29
 	Frame: function:'require', file:'', line: 1, column: 266
...

**Comment by vtjon** [comment]
@sitefinitysteve I am wondering about the withOptions and style properties. I didn't see any updates on the other issue that you opened. Any ideas or workarounds? My iOS skills aren't great but I'd try a pull request if I had a good direction.

**Comment by sitefinitysteve** [comment]
I can't solve this until I hear from the team on how to handle the Closures... :/ they arent generated in the metadata at all so that has me concerned...

I opened a dedicated one to be safe as the other kinda just piggybacked on someone elses almost unrelated issue

https://github.com/NativeScript/ios-runtime/issues/769

**Comment by vtjon** [comment]
@sitefinitysteve I've been following along. I appreciate you looking into this. It will be interesting to see the issue response by Auth0. On the Auth0 Lock V2 migration guide, it says:

> Objective-C support
> 
> Lock v2 cannot be used from Objective-C, since its public API relies on Swift features and that makes them unavailable in ObjC codebases.
> 
> If you are willing to have some Swift code in your existing application you can follow this guide on how to mix Objective-C and Swift and then use Lock v2 from the Swift files.
> 
> If that's not an option, we recommend sticking with Lock v1 or using Auth0.swift to build your own interface for user logins and signups.

https://auth0.com/docs/libraries/lock-ios/v2/migration#requirements

Do you think this is a concern? I'm not sure what the history is here but I think your plugin originally supported V1?

**Comment by sitefinitysteve** [comment]
Soliciting feedback: Okay so I have the issue in to style\set options on the lock via swift is problematic because they dont expose to objective C with lock (trivial change, but they havent responded to the ticket yet)

What if instead we go with the pure ios\android libs to authenticate instead of using Auth0 Lock?  Would mean you'd need your own login UIs instead of the auto-gen Lock, but I mean you'd want that anyway right?

**Comment by vtjon** [comment]
I think there are definite advantages to the lock product. The biggest seems to be the ability to add/remove social providers through the auth0 control panel. Of course, if I can't change the layout on iOS. I won't have any choice. 

I wonder if the Lock component is helping on the social login auth process. I do not know if there are complexities that we have to deal with if we use pure libs. I think this would be a deciding factor in my opinion.

**Comment by sitefinitysteve** [comment]
You are more than right... not needing to push out a new app version is a HUGE plus.  Perhaps you could assist me by tweeting about it or weighting in on the Git issue to maybe show them it's important?  Honestly it's like an attribute to apply and it should *just work* fine.

**Comment by vtjon** [comment]
Do we know what the downsides are of reverting back to v1 of the lock component for iOS?

**Comment by sitefinitysteve** [comment]
I don't want to :/ Inconsistant API, its really not supported anymore.  V2 is basically the same as android which is *fantastic* for being cross platform.  I'd rather more explore the option of Auth0 helping us out and exposing the attrib :/

**Comment by vtjon** [comment]
That is understandable and what I expected. I commented on your issue. I'll try to find some other ways to prod them.

**Comment by sitefinitysteve** [comment]
Thx @vtjon 

Referenced tweet: https://twitter.com/stevemcniven/status/870847449212088321

**Comment by charsleysa** [comment]
@budilovskiy @arpit2438735  @vtjon 
Starting with version 2.0.0 this library has been rewritten to use Auth0 Universal Login and support for previous versions will be dropped.
If this problem still exists when 2.0.0 is released please create a new issue. Thanks!
