### ISSUE TITLE
is this working on android?

### ISSUE THREAD

**Issue by lynsei** [sitefinitysteve/nativescript-auth0#2]
I can't get it to run with out tons of build errors on lollipop

**Comment by lynsei** [comment]
also: your links in your docs are broken to: https://auth0.com/docs/quickstart/native/ios-objc/ *

**Comment by lynsei** [comment]
Here's a screenshot  http://i.imgur.com/P6OoMKt.png

**Comment by lynsei** [comment]
that's straight running "tns run android" from the demo and a 5.1-x64 HAXM emulator running gradle 2.14 & node 5.12.0 x 64 on win 10

**Comment by sitefinitysteve** [comment]
Yeah sorry, gonna have to hang tight like 2 weeks, waiting on an implimentation from the {N} team to be released sorry... it was working, but 2.0 borked it, they went back and fixed a few things for me.

**Comment by nigel-dewar** [comment]
Hi Mate, any word on this as of yet? Good on ya for working out a workaround for this thing. chers

**Comment by sitefinitysteve** [comment]
Yep, working on it with the team, there was a small bug in the class generator that's fixed now, but not blocking for me

Hang tight

**Comment by nigel-dewar** [comment]
Cool ok so it is working for you, and you are still working with the team to improve it? 

or.... its not working and 'hang tight' means , just wait. 'It will be working in the future'?

Sorry I am confused as to what the status is.

Cheers for your work on this mate.

**Comment by sitefinitysteve** [comment]
Status is activly working with the ns android guys to iron out some issues, but should be okay soon... Hang tight, sorry :)

**Comment by nigel-dewar** [comment]
Roger that, cool thanks mate ☺

**Comment by nigel-dewar** [comment]
yo yo Steve, this baby good to go or still hangin?

**Comment by sitefinitysteve** [comment]
Workin on it, iOS no longer even builds here (sigh) and the droid side just throwing errors then crashes at runtime.  IN THEORY it should all now work... trying to sort it out with the guys

**Comment by nigel-dewar** [comment]
Oh bummer. Thanks for the update though. Im going to give identityserver4 a crack. If I succeed Ill share a sample with you as, I think it could serve well for those whom want auth for multiple id providers.

**Comment by sitefinitysteve** [comment]
Hang on... Telerik is dating it works on their end... I'm gonna go check dependencies

**Comment by nigel-dewar** [comment]
Ok, sweet. would be brill if case...

**Comment by sitefinitysteve** [comment]
Okay so I have it loading on android now (iOS still borked, unsure of that yet)...but now that its loading I should be able to finish it, hang tight

**Comment by nigel-dewar** [comment]
Nice work Steve. your the Man!!!

Sent from Samsung Mobile

-------- Original message --------
From: Steve McNiven-Scott
Date:19/11/2016 13:18 (GMT+10:00)
To: sitefinitysteve/nativescript-auth0
Cc: nigel-dewar , Comment
Subject: Re: [sitefinitysteve/nativescript-auth0] is this working on android? (#2)

Okay so I have it loading on android now (iOS still borked, unsure of that yet)...but now that its loading I should be able to finish it, hang tight

##

**Comment by sitefinitysteve** [comment]
Hang tight dude, auth0 totally changed this all up on me, no more broadcast receivers :)  Priority 1 for me though

**Comment by nigel-dewar** [comment]
No worries dude. Work in progress.

Sent from Samsung Mobile

-------- Original message --------
From: Steve McNiven-Scott
Date:21/11/2016 10:33 (GMT+10:00)
To: sitefinitysteve/nativescript-auth0
Cc: nigel-dewar , Comment
Subject: Re: [sitefinitysteve/nativescript-auth0] is this working on android? (#2)

Hang tight dude, auth0 totally changed this all up on me, no more broadcast receivers :) Priority 1 for me though

##

**Comment by sitefinitysteve** [comment]
...so crazy close on this right now, I just saw the v2 lock screen on android which is a first

**Comment by nigel-dewar** [comment]
Freaking awesome!!!


Sent from Samsung Mobile


-------- Original message --------
From: Steve McNiven-Scott
Date:07/12/2016 02:42 (GMT+10:00)
To: sitefinitysteve/nativescript-auth0
Cc: nigel-dewar , Comment
Subject: Re: [sitefinitysteve/nativescript-auth0] is this working on android? (#2)


...so crazy close on this right now, I just saw the v2 lock screen on android which is a first

-

**Comment by sitefinitysteve** [comment]
Closing, android works now total API rewrite, latest stuff from Auth0
