### ISSUE TITLE
ParamBuilder.set doesn't work!

### ISSUE THREAD

**Issue by alexgtn** [sitefinitysteve/nativescript-auth0#20]
Trying to set an auth parameter.
This is what I'm trying to accomplish: https://auth0.com/docs/libraries/lock/v10/sending-authentication-parameters

My code:
```
var paramBuilder = com.auth0.android.authentication.ParameterBuilder.newBuilder();
var authenticationParameters = paramBuilder.set("state", 12345); 
builder.withAuthenticationParameters(authenticationParameters);
```

The lock doesn't appear after this.

**Comment by charsleysa** [comment]
@AGutan  
Starting with version 2.0.0 this library has been rewritten to use Auth0 Universal Login and support for previous versions will be dropped.
If this problem still exists when 2.0.0 is released please create a new issue. Thanks!
