### ISSUE TITLE
Android error after authentication.

### ISSUE THREAD

**Issue by alexgtn** [sitefinitysteve/nativescript-auth0#21]
Error after successful auth on Android.

Compiler complains about this.refresh() in auth0.js.

Check.

**Comment by sitefinitysteve** [comment]
Yep you are right, works in iOS because of the TS closure, hang on

**Comment by sitefinitysteve** [comment]
Give it a try now on the latest npm version?

**Comment by alexgtn** [comment]
@sitefinitysteve still the same issue. Error after auth. But if I close the app and reopen, I see the Home screen with all the credentials.

**Comment by sitefinitysteve** [comment]
v1.2.3?

**Comment by alexgtn** [comment]
@sitefinitysteve Yep. I deleted the old plugin version and ran again tns plugin add nativescript-auth0

**Comment by sitefinitysteve** [comment]
Okay tested 1.2.4 you should be good now... didn't assign the local resolve
