### ISSUE TITLE
How to log out user?

### ISSUE THREAD

**Issue by bbenson36** [sitefinitysteve/nativescript-auth0#22]
I've been trying to add log out functionality to my app and I noticed it was still returning true for `hasValidToken()` even after calling `clearTokens()`

Looking closer at the code I saw:
```
public clearTokens(): void{
        appSetttings.remove(Auth0Lock._tokenKey);
};
```
but  `hasValidToken()` is checking `this.credientials.accessToken` which isn't loaded from appsettings until `refresh()` is called:

```
    public refresh(): void{
        if (appSetttings.hasKey(Auth0Lock._tokenKey)) {
            var data = JSON.parse(appSetttings.getString(Auth0Lock._tokenKey));
            this.credientials = {
                accessToken: data.accessToken,
                idToken: data.idToken,
                refreshToken: data.refreshToken,
            };
        }
    };
```

Which won't refresh because `appSetttings.hasKey(Auth0Lock._tokenKey)` is false after calling `clearTokens()`

Is there a good way to log out?

If not I propose adding the following to `clearTokens()`

```
public clearTokens(): void{
        appSetttings.remove(Auth0Lock._tokenKey);
        this.credientials = { // should cause hasValidToken() to fail
            accessToken: "",
            idToken: "",
            refreshToken: ""
        };
};
```

**Comment by sitefinitysteve** [comment]
Good catch!  Will fix thx!

**Comment by charsleysa** [comment]
@willy3615 
Starting with version 2.0.0 this library has been rewritten to use Auth0 Universal Login and support for previous versions will be dropped.
If this problem still exists when 2.0.0 is released please create a new issue. Thanks!
