### ISSUE TITLE
Return to application after login

### ISSUE THREAD

**Issue by budilovskiy** [sitefinitysteve/nativescript-auth0#24]
There is some changes in new version of Lock for Android.
Now it needs to add the Manifest Placeholders for the Auth0 Domain and the Auth0 Scheme properties in build.gradle file and there is no need to define an intent-filter inside the LockActivity.
But now with this changes callback is not handled automatically with the nativescript application.

**Comment by Dashue** [comment]
Hitting this as well, were you able to solve this?

**Comment by budilovskiy** [comment]
No, unfortunately I could not solve this problem

**Comment by charsleysa** [comment]
@budilovskiy @Dashue 
Starting with version 2.0.0 this library has been rewritten to use Auth0 Universal Login and support for previous versions will be dropped.
If this problem still exists when 2.0.0 is released please create a new issue. Thanks!
