### ISSUE TITLE
Android locked to version 25

### ISSUE THREAD

**Issue by westlakem** [sitefinitysteve/nativescript-auth0#27]
When I install this plugin on a fresh NX install, it complains about the version of Android needed.  

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processF0DebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.3.1) from [com.android.support:customtabs:25.3.1] AndroidManifest.xml:24:9-31
        is also present at [com.android.support:design:26.0.0-alpha1] AndroidManifest.xml:27:9-38 value=(26.0.0-alpha1).
        Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:22:5-24:34 to override.

Is it possible to make it version agnostic or ^25?

**Comment by uzarsalan** [comment]
Same issue

**Comment by charsleysa** [comment]
@westlakem @uzarsalan 
Starting with version 2.0.0 this library has been rewritten to use Auth0 Universal Login and support for previous versions will be dropped.
If this problem still exists when 2.0.0 is released please create a new issue. Thanks!
