### ISSUE TITLE
Error :  java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference

### ISSUE THREAD

**Issue by kriefsacha** [sitefinitysteve/nativescript-auth0#29]
Hello everyone,

To begin with , i'm quite new with this so excuse me if i forgot some informations and already thanks for your help.

First , my tns version is 4.1.2.
The version of tns-android is 4.1.3.
The version of nativescript-auth0 is 2.0.0.

I did as you saied , added to the Android Manifest : 

```
		<activity
            android:name="com.auth0.android.provider.RedirectActivity"
            tools:node="replace">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="jarggon.eu.auth0.com"
                    android:pathPrefix="/android/org.nativescript.JarggonTranslatorApp/callback"
                    android:scheme="https" />
            </intent-filter>
        </activity>
```

In my component i have : 

```
     lock.show().then((res) => {
      console.log('success');
    }, function (error) {
      console.log(error);
    }); 
```

With my instance of lock , everything is perfectly fine.

But when i'm running the app by " tns run android " i get this : 

> JS:    Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
> JS:     android.support.v4.content.LocalBroadcastManager.getInstance(LocalBroadcastManager.java:102)
> JS:     com.auth0.android.lock.Lock.initialize(Lock.java:144)
> JS:     com.auth0.android.lock.Lock.access$200(Lock.java:56)
> JS:     com.auth0.android.lock.Lock$Builder.build(Lock.java:236)
> JS:     com.tns.Runtime.callJSMethodNative(Native Method)
> JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
> JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:970)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:954)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:946)
> JS:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
> JS:     android.app.Activity.performCreate(Activity.java:7041)
> JS:     android.app.Activity.performCreate(Activity.java:7032)
> JS:     android.app.Instrumentation.callActivityOnCre...

I know if from the console.log of the error in the lock.show() function , but i don't understand why..

I also tried to add a reference.d.ts file in the root and put in it : 

```
/// <reference path="./node_modules/nativescript-auth0/typings/Auth0.ios.d.ts" />
/// <reference path="./node_modules/nativescript-auth0/typings/Lock.ios.d.ts" />
```

But i get something like 30 errors at runtime like : 

> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(2,43): error TS2552: Cannot find name 'NSObject'. Did you mean 'Object'?
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(8,42): error TS2304: Cannot find name 'NSURL'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(10,42): error TS2304: Cannot find name 'NSURL'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(10,58): error TS2304: Cannot find name 'NSURLSession'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(12,153): error TS2304: Cannot find name 'NSDictionary'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(12,195): error TS2304: Cannot find name 'NSError'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(12,208): error TS2304: Cannot find name 'NSDictionary'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(14,45): error TS2304: Cannot find name 'NSURL'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(16,52): error TS2304: Cannot find name 'NSURL'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(16,68): error TS2304: Cannot find name 'NSURLSession'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(18,118): error TS2304: Cannot find name 'NSDictionary'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(18,160): error TS2304: Cannot find name 'NSError'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(20,151): error TS2304: Cannot find name 'NSDictionary'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(20,193): error TS2304: Cannot find name 'NSError'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(22,93): error TS2304: Cannot find name 'NSError'.

I don't know what else i can do .. thanks for your help , if you need any information tell me ..

**Comment by charsleysa** [comment]
@kriefsacha Hi there.

v2.0.0 is currently being worked on and hasn't yet been released.
It is a complete rewrite that goes away from using the Lock libraries and uses the Universal Login that is recommended by Auth0.

Here are the instructions for the currently available version (v1.2.7)
https://github.com/sitefinitysteve/nativescript-auth0/tree/d2e40f4d5c60199072133c1c1330ed81f6d28b7d

**Comment by kriefsacha** [comment]
@charsleysa Hi !

First thank you for your fast answer.

I tried before with 1.2.7 and it didn't work so i though maybe i have to upgrade.

I did it again from scratch right now in a new project with the 1.2.7 version.

I did just as your link says.

I got : 

> C:\Users\krief\Documents\GitHub\jarggon\JarggonTranslatorApp\platforms\android\app\src\main\AndroidManifest.xml Error:
>         Attribute data@host at AndroidManifest.xml requires a placeholder substitution but no value for <auth0Domain> is provided.
> C:\Users\krief\Documents\GitHub\jarggon\JarggonTranslatorApp\platforms\android\app\src\main\AndroidManifest.xml Error:
>         Attribute data@scheme at AndroidManifest.xml requires a placeholder substitution but no value for <auth0Scheme> is provided.

I already got it before and i saw at this time on a link that i had to add on the build.gradle : 

`manifestPlaceholders = [auth0Domain: "jarggon.eu.auth0.com", auth0Scheme: "https"]`

at the " android { defaultConfig { " part.

After this was resolved , I got the same errors from the reference.d.ts file that i created at the root of the folder with the "Cannot find name .. ". : 

> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(2,43): error TS2552: Cannot find name 'NSObject'. Did you mean 'Object'?
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(8,42): error TS2304: Cannot find name 'NSURL'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(10,42): error TS2304: Cannot find name 'NSURL'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(10,58): error TS2304: Cannot find name 'NSURLSession'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(12,153): error TS2304: Cannot find name 'NSDictionary'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(12,195): error TS2304: Cannot find name 'NSError'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(12,208): error TS2304: Cannot find name 'NSDictionary'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(14,45): error TS2304: Cannot find name 'NSURL'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(16,52): error TS2304: Cannot find name 'NSURL'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(16,68): error TS2304: Cannot find name 'NSURLSession'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(18,118): error TS2304: Cannot find name 'NSDictionary'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(18,160): error TS2304: Cannot find name 'NSError'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(20,151): error TS2304: Cannot find name 'NSDictionary'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(20,193): error TS2304: Cannot find name 'NSError'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(22,93): error TS2304: Cannot find name 'NSError'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(26,164): error TS2304: Cannot find name 'NSDictionary'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(26,218): error TS2304: Cannot find name 'NSDictionary'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(26,260): error TS2304: Cannot find name 'NSError'.
> node_modules/nativescript-auth0/typings/Auth0.ios.d.ts(28,103): error TS2304: Cannot find name 'NSError'.

Something like 50 of them ..

and with this also got the same error .. : 

> JS:     Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
> JS:     android.support.v4.content.LocalBroadcastManager.getInstance(LocalBroadcastManager.java:102)
> JS:     com.auth0.android.lock.Lock.initialize(Lock.java:144)
> JS:     com.auth0.android.lock.Lock.access$200(Lock.java:56)
> JS:     com.auth0.android.lock.Lock$Builder.build(Lock.java:236)
> JS:     com.tns.Runtime.callJSMethodNative(Native Method)
> JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
> JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:970)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:954)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:946)
> JS:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
> JS:     android.app.Activity.performCreate(Activity.java:7041)
> JS:     android.app.Activity.performCreate(Activity.java:7032)
> JS:     android.app.Instrumentation.callActivityOnCre...
> 

I really don't know what to do .. thanks for all !

**Comment by charsleysa** [comment]
@kriefsacha could you please post some code and give some context on where you are calling the lock from?

I can't see anything obvious that could cause that crash, though I think it may be caused by the lock being called before NativeScript has properly setup an activity.

The "Cannot find name …" errors seem to be related with the plugin being compiled against older type definitions which have had their file locations changed since.

**Comment by kriefsacha** [comment]
@charsleysa  thank you for your answer.

My component is like this : 

```
import { Component, OnInit } from "@angular/core";
import { Auth0Lock } from "nativescript-auth0";


@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html"
})
export class HomeComponent implements OnInit {
    constructor() {
    }

    ngOnInit(): void {
        var lock = new Auth0Lock({
            clientId: 'vHfWU8tWDEGTFosuqL9QnGG1RfsFh0T6',
            domain: 'jarggon.eu.auth0.com',
            scope: ["offline_access openid"]
          });
        lock.show().then((res) => {
            //goToHomeOrWhatevs(); 
            console.log('success');
          }, function (error) {
            console.log(error);
          }); 
    }
}
```

i tried to initialize the lock in other places like in a service , as a property .. nothing changes.

And ok for the "Cannot find name.." problems but how can i fix this ? Do i even need for two references for what i need to do ? 

Thanks for all !

**Comment by charsleysa** [comment]
@kriefsacha I think the issue may be that the code is inside ngOnInit.

As far as I know, NativeScript hasn't finished initializing the views at that point.

Try using the ngAfterViewInit lifecycle event.

As for the "Cannot find name..." errors, I think this would require a new version of the library to be published.

**Comment by kriefsacha** [comment]
@charsleysa  first i puted the references in comments as you saied i can't for now.

my component is now like this : 

```
import { Component, OnInit, AfterViewInit } from "@angular/core";
import { Auth0Lock } from "nativescript-auth0";

@Component({
    selector: "Home",
    moduleId: module.id,
    templateUrl: "./home.component.html"
})
export class HomeComponent implements AfterViewInit {

    constructor() {
    }

    ngAfterViewInit(): void {
        var lock = new Auth0Lock({
            clientId: 'vHfWU8tWDEGTFosuqL9QnGG1RfsFh0T6',
            domain: 'jarggon.eu.auth0.com',
            scope: ["offline_access openid"]
        });
        // Init your component properties here.
        lock.show().then((res) => {
            console.log('success');
        }, function (error) {
            console.log(error);
        });
    }
}
```

And i still get : 

> JS: Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference
> JS:     android.support.v4.content.LocalBroadcastManager.getInstance(LocalBroadcastManager.java:102)
> JS:     com.auth0.android.lock.Lock.initialize(Lock.java:144)
> JS:     com.auth0.android.lock.Lock.access$200(Lock.java:56)
> JS:     com.auth0.android.lock.Lock$Builder.build(Lock.java:236)
> JS:     com.tns.Runtime.callJSMethodNative(Native Method)
> JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
> JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:970)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:954)
> JS:     com.tns.Runtime.callJSMethod(Runtime.java:946)
> JS:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:18)
> JS:     android.app.Activity.performCreate(Activity.java:7041)
> JS:     android.app.Activity.performCreate(Activity.java:7032)
> JS:     android.app.Instrumentation.callActivityOnCre...

**Comment by charsleysa** [comment]
@kriefsacha sorry I can't be much more help but I don't know NativeScript with Angular very well.

Can you please verify that the Angular lifecycle event occurs after the views have been setup?
You should be able to do that by including the following import
```
import * as frameModule from "ui/frame";
```
and then in your lifecycle event adding
```
console.log(frameModule.topmost().android.activity)
```

If the result is undefined then the Angular lifecycle hooks aren't properly connected by NativeScript.

EDIT: posted prematurely

**Comment by kriefsacha** [comment]
@charsleysa  you help a lot don't worry.

I actually get undefined yes ..

Do you know how i can fix that issue maybe ? I'm also quite new ..

Thanks for all !

**Comment by charsleysa** [comment]
@kriefsacha I don't know how to fix the issue but I have seen some workarounds online that have worked for some people.

One of them is having a container inside your view (e.g. StackLayout) and using its loaded event (e.g. loaded="myLoadedEventHandler") and then executing your code inside the event handler.

What's needed is for the current activity to be available to the topmost Frame at the time which your code is executed as the Lock needs to grab the activity context.

**Comment by kriefsacha** [comment]
It's actually working with the loaded event of the GridLayout ! Thanks a lot for your help @charsleysa  ! You are the best ! I will ask if i need something , thank you for all !!

**Comment by kriefsacha** [comment]
@charsleysa  i'm so sorry to bother you ..

I now have an error after the login , on my phone not on the console

> Cannot GET /android/org.nativescript.JarggonTranslatorApp/callback

I puted on the callback urls in the dashboard of auth0 , and my lock is now like this : 

```
        lock.show().then((res) => {
            //goToHomeOrWhatevs(); 
            console.log('success' ,res);
            this.router.navigate(['logged']);
        }, function (error) {
            console.log('lock error ' + error);
        });
```

Did i do something wrong ? Thank you for all !

**Comment by kriefsacha** [comment]
@charsleysa i'm so sorry to bother you ..

Now i have an error message on my phone when i try to push the loggin button : 

> THERE WAS AN ERROR PROCESSING THE SIGN IN


My lock is now like that : 

```
        lock.show().then((res) => {
            //goToHomeOrWhatevs(); 
            console.log('success' ,res);
            this.router.navigate(['logged']);
        }, function (error) {
            console.log('lock error ' + error);
        });
```

And i don't have any error in the console .. maybe you know where it came from ..

**Comment by charsleysa** [comment]
@kriefsacha that looks like the app hasn't properly registered the url as for redirecting back to the app.

Double check that AndroidManifest part is correctly implemented.

**Comment by kriefsacha** [comment]
@charsleysa  I did a triple check , seems okay for me ...

this is the Manifest : 

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="__PACKAGE__"
	android:versionCode="10000"
	android:versionName="1.0">

	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>

	<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>

	<application
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="@string/app_name"
		android:theme="@style/AppTheme">

		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboardHidden|orientation|screenSize"
			android:theme="@style/LaunchScreenTheme">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
		<!--Auth0 Lock-->
      <activity
          android:name="com.auth0.android.lock.LockActivity"
          android:label="Classic Lock"
          android:launchMode="singleTask"
          android:screenOrientation="portrait"
          android:theme="@style/Lock.Theme">
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />

              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />

              <data
                  android:host="nativescript.auth0.com"
                  android:pathPrefix="/android/org.nativescript.JarggonTranslatorApp/callback"
                  android:scheme="https" />
          </intent-filter>
      </activity>
      <!--Auth0 Lock End-->

  <!--Auth0 Lock Embedded WebView-->
      <activity
          android:name="com.auth0.android.provider.WebAuthActivity" />
      <!--Auth0 Lock Embedded WebView End-->
	</application>
</manifest>

```

At the                  

>  android:pathPrefix="/android/org.nativescript.JarggonTranslatorApp/callback"


part , it was 

> __PACKAGE__

 but i though maybe it's because i need to put the applicationId instead but both don't work ..

**Comment by charsleysa** [comment]
The following line should have your Auth0 host name not the nativescript demo host name.
android:host="nativescript.auth0.com"

So it should be
android:host="jarggon.eu.auth0.com"

**Comment by kriefsacha** [comment]
@charsleysa  so sorry .. How i didn't saw that ..

I changed it but i have the same error .. 

The manifest is now like that

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="__PACKAGE__"
	android:versionCode="10000"
	android:versionName="1.0">

	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>

	<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>

	<application
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="@string/app_name"
		android:theme="@style/AppTheme">

		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboardHidden|orientation|screenSize"
			android:theme="@style/LaunchScreenTheme">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>
		<!--Auth0 Lock-->
      <activity
          android:name="com.auth0.android.lock.LockActivity"
          android:label="Classic Lock"
          android:launchMode="singleTask"
          android:screenOrientation="portrait"
          android:theme="@style/Lock.Theme">
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />

              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />

              <data
                  android:host="jarggon.eu.auth0.com"
                  android:pathPrefix="/android/org.nativescript.JarggonTranslatorApp/callback"
                  android:scheme="https" />
          </intent-filter>
      </activity>
      <!--Auth0 Lock End-->

  <!--Auth0 Lock Embedded WebView-->
      <activity
          android:name="com.auth0.android.provider.WebAuthActivity" />
      <!--Auth0 Lock Embedded WebView End-->
	</application>
</manifest>

```

Again tried to change the pathPrefix part with the __PACKAGE__ but doesn't work ...

**Comment by charsleysa** [comment]
Do you see anything in the logs in the Auth0 Dashboard?

**Comment by kriefsacha** [comment]
@charsleysa No nothing about that ...

**Comment by kriefsacha** [comment]
I puted those both callback url's on the dashboard to be sure .. : 

> https://jarggon.eu.auth0.com/android/org.nativescript.JarggonTranslatorApp/callback, https://jarggon.eu.auth0.com/android/__PACKAGE__/callback

**Comment by charsleysa** [comment]
@kriefsacha there should be an output in the Android logs containing `Failed to authenticate the user`.

Can you please post the full log for that? It should contain more information on what exactly is failing.

**Comment by kriefsacha** [comment]
I'm so sorry but i'm trying to search the logs you are talking about and i don't find it ..
If you know where it should be ..

**Comment by kriefsacha** [comment]
I'm still with the same issue @charsleysa ...

I may think that the callback url is not good ..

I tried to changed it a couple times and i have the same ..

In the Manifest it's now : 
```

      <activity
          android:name="com.auth0.android.lock.LockActivity"
          android:label="Classic Lock"
          android:launchMode="singleTask"
          android:screenOrientation="portrait"
          android:theme="@style/Lock.Theme">
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />

              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />

              <data
                  android:host="jarggon.eu.auth0.com"
                  android:pathPrefix="/android/__PACKAGE__/callback"
                  android:scheme="https" />
          </intent-filter>
      </activity>
```

As your link says it should be.

For the callback url i puted : 

> https://jarggon.eu.auth0.com/android/__PACKAGE__/callback

as i think it should be ..

I also tried : 

> https://jarggon.eu.auth0.com/android/org.nativescript.JarggonTranslatorApp/callback


But same ..

**Comment by kriefsacha** [comment]
@charsleysa  I found it !! Someone told me to run it with Android Studio instead of the console and the "tns run android". Hope it helps you understand ..

> 08-05 16:22:43.227 13798-13872/org.nativescript.JarggonTranslatorApp E/LockActivity: Failed to authenticate the user: An error occurred when trying to authenticate with the server.
>     com.auth0.android.authentication.AuthenticationException: An error occurred when trying to authenticate with the server.
>         at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:23)
>         at com.auth0.android.request.internal.AuthenticationErrorBuilder.from(AuthenticationErrorBuilder.java:9)
>         at com.auth0.android.request.internal.BaseRequest.parseUnsuccessfulResponse(BaseRequest.java:137)
>         at com.auth0.android.request.internal.SimpleRequest.onResponse(SimpleRequest.java:68)
>         at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
>         at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
>         at java.lang.Thread.run(Thread.java:764)

**Comment by charsleysa** [comment]
@kriefsacha it seems that some functionality is turned off by default / completely unavailable as Auth0 moves forward and deprecates native Lock UI on mobile apps.
https://github.com/auth0/Lock.Android#notes-on-embedded-authentication

Because of this they are pushing for Universal Login which this plugin currently does not yet have but is currently being worked on for v2.

**Comment by kriefsacha** [comment]
It works !! I had to activate the Password Grand Type on the auth0 Dashbord ...

I now see " Authentication Success" , the accessToken etc ..

Thank you for all ! @charsleysa  you are the best .. I hope that i will not bother you again !

**Comment by charsleysa** [comment]
@kriefsacha no worries. Glad it's working for you!
