### ISSUE TITLE
auth0.initalize is not a function

### ISSUE THREAD

**Issue by chrishawn** [sitefinitysteve/nativescript-auth0#3]
trying to get the plugin to my ios project working, not sure what i am doing wrong, i can't get past

`file:///app/app.js:22:28: JS ERROR TypeError: auth0.initalize is not a function. (In 'auth0.initalize()', 'auth0.initalize' is undefined)
`

**Comment by sitefinitysteve** [comment]
Has the plugin been referenced? https://github.com/sitefinitysteve/nativescript-auth0/blob/master/demo/app/app.js#L2

**Comment by chrishawn** [comment]
it has but i am doing it in typescript (maybe something not right), generated js looks right though

i added the plugin with `tns plugin add nativescript-auth0`
then did a `pod install, pod setup`
and i added the code below

```
import { platformNativeScriptDynamic } from "nativescript-angular/platform";
import { AppModule } from "./app.module";

//Auth0 plugin:
var auth0 = require("nativescript-auth0");
var application = require("application");
declare var UIResponder: any;
declare var UIApplicationDelegate: any;

if (application.ios) {
    var __extends = this.__extends || function (d, b) {
            for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
            function __() { this.constructor = d; }
            __.prototype = b.prototype;
            d.prototype = new __();
        };

    var appDelegate = (function (_super) {
        __extends(appDelegate, _super);
        function appDelegate() {
            _super.apply(this, arguments);
        }

        appDelegate.prototype.applicationDidFinishLaunchingWithOptions = function (application, launchOptions) {
            auth0.initalize();
        };

        (appDelegate as any).ObjCProtocols = [UIApplicationDelegate];
        return appDelegate;
    })(UIResponder);
    application.ios.delegate = appDelegate;
}else{
    //Android
    auth0.initalize();
}
//End Auth0 plugin

platformNativeScriptDynamic().bootstrapModule(AppModule);
```

**Comment by sitefinitysteve** [comment]
Gah, okay yeah I need to update the demo for TS... can I get back to you shortly?  I think it's the delegate code on TS is way simpler

**Comment by chrishawn** [comment]
yeah that would be great, i feel close, just missing something... but yeah auth0 support is a big stopping block for me doing more with nativescript on this project

**Comment by sitefinitysteve** [comment]
It's big for me too, Android side still waiting on a bugfix coming in 2.4 btw

**Comment by chrishawn** [comment]
still no word?

**Comment by sitefinitysteve** [comment]
Closing, android works now total API rewrite, latest stuff from Auth0
