### ISSUE TITLE
Release version 2.0.0

### ISSUE THREAD

**Issue by charsleysa** [sitefinitysteve/nativescript-auth0#31]
Need to prep and release version 2.0.0 to npm.

@sitefinitysteve, how would you like to do this?
I don't think I have access to publish to npm for this library.

**Comment by santanubasu** [comment]
If this is not imminent, is there a way we can use the git project as an NPM dep?  Tried doing this but ran into the issue that there is no package.json in the project root.

**Comment by sitefinitysteve** [comment]
I'll hook this up tomorrow, sorry about the delay... I'll try to share out the publish

**Comment by sitefinitysteve** [comment]
2.0.0 has been publushed @charsleysa I added you to npm as a maintainer... might want to enable 2fa, I see you have it disabled :)
