### ISSUE TITLE
cannot install v2

### ISSUE THREAD

**Issue by wissemchiha** [sitefinitysteve/nativescript-auth0#32]
I can't install the last version of this repository, when i make  **tns plugin install nativescript-auth0** the installed version is 1.2.7
also i tried to make **tns plugin install nativescript-auth0@2.0.0** and not work
please help ?

**Comment by charsleysa** [comment]
2.0.0 has not yet been published to npm, please refer to #31 for tracking progress on the release.

**Comment by wissemchiha** [comment]
ok, thank you
