### ISSUE TITLE
Some questions on docs

### ISSUE THREAD

**Issue by santanubasu** [sitefinitysteve/nativescript-auth0#33]
A few docs questions.

In the android section it says "Requires your references.d.ts file to have android pointing to", it sems like there was a missing part to this instruction?

In the example code, there is this:

`import { Auth0Lock } from "nativescript-auth0";
`

Should that be:

`import { Auth0 } from "nativescript-auth0";`

given the code that follows after that?

**Comment by charsleysa** [comment]
Hi @santanubasu 

In your NativeScript project you will have a file in the root folder called `references.d.ts` that will contain references for type definitions. If you do not have this file then you probably don't use it (and you don't necessarily need it).

If you do have this file and you do import the android platform definitions from NativeScript then you'll need to use android-27 as that is what this library uses.

These instructions are for those edge case projects which are affected by this, most projects usually don't use this file (either the file doesn't exist or it's only got comments in it). I'll try to make this a bit more clear.

As for the code example, you are correct, that is a typo leftover from the previous version example.

**Comment by charsleysa** [comment]
@santanubasu the readme has been updated, hopefully this addresses your questions.
Please feel free to reopen this issue if you have more questions.
