### ISSUE TITLE
Update 2.0

### ISSUE THREAD

**Issue by kriefsacha** [sitefinitysteve/nativescript-auth0#35]
Hi,

I had the 1.2.7 version with the lock and it was great , i just wanted to use my custom login that i did on auth0.

So after i saw you did a 2.0 version with it i added it.

And then i see it's just redirecting me in a browser page..

I don't understand anymore what is your library helping ..

I could just do the same with a webview ..

I liked the idea that it's in my application himself , if it's on a browser that's not great for security and visually it's also not so great ..

Maybe i missed something if it's the case i'm sorry , i just try to understand.

Thank you for your job !

**Comment by charsleysa** [comment]
Hi @kriefsacha

Starting with version 2.0 this library has moved away from embedded login and now implements login flow for Auth0 Universal Login which is recommended by Auth0.

Auth0 Universal Login is better for security and provides a more consistent user authentication experience. You can read more about it here (direct from Auth0): https://auth0.com/docs/hosted-pages/login

What you are seeing isn't quite the same as a webview. Web views are embedded into the app and can be manipulated by the app. This library uses secure browser instances that are detached from the app and can't be manipulated.

This library, by default, behind the scenes executes a Authorization Code Grant Flow with PKCE, you can read more about it here (direct from Auth0): https://auth0.com/docs/api-auth/tutorials/authorization-code-grant-pkce

Let me know if this clears things up! 

Cheers, 
Stefan

**Comment by kriefsacha** [comment]
Hi @charsleysa ,

Thanks for your help,

I understand, but the functionnality in native android and ios apps also works the same way ?

If not , why do your library use it like that ?

Sorry i just try to understand,

Thank you for all !

Sacha

**Comment by charsleysa** [comment]
Not too sure what you mean by "I understand, but the functionnality in native android and ios apps also works the same way ?".

This library is a port of the Auth0 libraries, see here for Android library: https://auth0.com/docs/libraries/auth0-android

As Auth0 has deprecated (and removed) some older APIs and functionality, this library is OIDC Conformant (without the option to turn it off).

**Comment by kriefsacha** [comment]
Okay no problem we will use it like that,

So now i puted the last version of the library , my androidManifest is like that : 

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	package="__PACKAGE__"
	xmlns:tools="http://schemas.android.com/tools"
	android:versionCode="10000"
	android:versionName="1.0">

	<supports-screens
		android:smallScreens="true"
		android:normalScreens="true"
		android:largeScreens="true"
		android:xlargeScreens="true"/>

	<uses-sdk
		android:minSdkVersion="17"
		android:targetSdkVersion="__APILEVEL__"/>

	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
	<uses-permission android:name="android.permission.INTERNET"/>

	<application
		android:name="com.tns.NativeScriptApplication"
		android:allowBackup="true"
		android:icon="@drawable/icon"
		android:label="@string/app_name"
		android:theme="@style/AppTheme">

		<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
		
		<activity
			android:name="com.tns.NativeScriptActivity"
			android:label="@string/title_activity_kimera"
			android:configChanges="keyboardHidden|orientation|screenSize"
			android:theme="@style/LaunchScreenTheme"
			android:screenOrientation="portrait">

			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />

			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity android:name="com.tns.ErrorReportActivity"/>

      <activity
          android:name="org.nativescript.auth0.RedirectActivity"
            tools:node="replace">
          <intent-filter>
              <action android:name="android.intent.action.VIEW" />

              <category android:name="android.intent.category.DEFAULT" />
              <category android:name="android.intent.category.BROWSABLE" />

              <data
                  android:host="jarggon.eu.auth0.com"
                  android:pathPrefix="/android/org.nativescript.JarggonTranslatorApp/callback"
                  android:scheme="https" />
          </intent-filter>
      </activity>
	  
	</application>
</manifest>
```

I have an Auth0Service like that 

```
import { Injectable } from '@angular/core';
import { Auth0 } from 'nativescript-auth0';

@Injectable()
export class Auth0Service {

  public lock: any
  constructor() {
    this.lock = new Auth0('vHfWU8tWDEGTFosuqL9QnGG1RfsFh0T6', 'jarggon.eu.auth0.com');
  }

}


```

And in my home component i have : 
```
    init() {
        this.auth0Service.lock.webAuthentication({ scope: "openid offline_access" }).then( (auth0res)=> {
            console.log('logged');
        }, (error) =>{
            console.log('lock error ' + error);
        });
    }

```

I have the right callback url in auth0 and added the password grant type.

But on my screen i see : 

> Cannot GET /android/org.nativescript.JarggonTranslatorApp/callback 

And on the logs of auth0 i see Sucess Login everytime i try .. Maybe you have an idea ?

**Comment by charsleysa** [comment]
Double check that your application ID matches.

I personally experienced this occurring too many times (inconsistent behavior) when developing an Android app in Kotlin with Auth0.

This seemed to be just an Android thing that sometimes happened.

I personally switch from using `https` to a custom scheme.

You can set this app in Auth0 by replacing the `https` in the callback address with `org.nativescript.JarggonTranslatorApp`.
Then update the manifest file so the line looks this `android:scheme="org.nativescript.JarggonTranslatorApp"`.
And then in your code when you call the Auth0.login function you add an extra property to the config object `scheme: 'org.nativescript.JarggonTranslatorApp'`.

**Comment by charsleysa** [comment]
@kriefsacha 

Here's the Auth service and Auth guard from one of our apps which deals with a few common needs that you may have as well (requires `nativescript-secure-storage` library)):
<details>
<summary>auth.service.ts</summary>

```ts
import { Injectable } from '@angular/core';
import { Auth0, Credentials } from 'nativescript-auth0';
import { SecureStorage } from 'nativescript-secure-storage';


@Injectable()
export class AuthService {

    private static AUTH0_CREDENTIALS: string = 'AUTH0_CREDENTIALS';

    private auth0: Auth0;

    private secureStorage: SecureStorage;

    AUTH0_SCOPE = 'openid email profile offline_access';
    AUTH0_SCHEME = '<your custom scheme>';

    // debug values
    AUTH0_DOMAIN = '<your domain>';
    AUTH0_CLIENTID = '<your client id>';

    AUTH0_AUDIENCE = '<your audience>';

    // production values
    // AUTH0_DOMAIN = '<your domain>';
    // AUTH0_CLIENTID = '<your client id>';

    // AUTH0_AUDIENCE = '<your audience>';

    // Store authentication data
    private credentials?: Credentials;

    constructor() {
        this.auth0 = new Auth0(this.AUTH0_CLIENTID, this.AUTH0_DOMAIN);

        this.secureStorage = new SecureStorage();

        const credentialsJson = this.secureStorage.getSync({ key: AuthService.AUTH0_CREDENTIALS });
        if (credentialsJson != null) {
            this.credentials = Credentials.initWithJson(JSON.parse(credentialsJson));
        }
    }

    public async login(): Promise<string> {
        const credentials = await this.auth0
            .webAuthentication({
                audience: this.AUTH0_AUDIENCE,
                scope: this.AUTH0_SCOPE,
                scheme: this.AUTH0_SCHEME
            });

        await this.secureStorage.set({
            key: AuthService.AUTH0_CREDENTIALS,
            value: JSON.stringify(credentials)
        });

        this.credentials = credentials;

        return credentials.idToken;
    }

    public logout(): void {
        this.secureStorage.removeSync({ key: AuthService.AUTH0_CREDENTIALS });
        this.credentials = undefined;
    }

    public async getAccessToken(): Promise<string> {
        // See if we have a valid token, if so just return it
        if (this.isLoggedIn) {
            return this.credentials.accessToken;
        } else {
            // If our token is not valid then it's possibly expired so try to renew it
            await this.renewCredentials();
            return this.credentials.accessToken;
        }
    }

    public async renewCredentials(): Promise<void> {
        const credentials = await this.auth0.renewCredentials(this.credentials.refreshToken);
        await this.secureStorage.set({
            key: AuthService.AUTH0_CREDENTIALS,
            value: JSON.stringify(credentials)
        });
        this.credentials = credentials;
    }

    get hasValidCredentials(): boolean {
        return this.credentials != null && this.credentials.refreshToken != null;
    }

    get isLoggedIn(): boolean {
        // Check if current date is before token
        // expiration and user is signed in locally
        return this.credentials != null && new Date() < this.credentials.expiresAt;
    }
}
```

</details>

<details>
<summary>auth.guard.ts</summary>

```ts
import { Injectable } from '@angular/core';
import { CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot, CanActivateChild } from '@angular/router';
import { RouterExtensions } from 'nativescript-angular/router';
import { Observable } from 'rxjs';
import { AuthService } from './auth.service';

@Injectable()
export class AuthGuard implements CanActivate, CanActivateChild {

    constructor(
        private authService: AuthService,
        private router: RouterExtensions
    ) { }

    canActivate(
        next: ActivatedRouteSnapshot,
        state: RouterStateSnapshot
    ): Observable<boolean> | Promise<boolean> | boolean {
        if (!this.authService.isLoggedIn) {
            if (this.authService.hasValidCredentials) {
                return this.authService
                    .renewCredentials()
                    .then(
                        () => true,
                        (error) => {
                            this.router.navigateByUrl('/login', { clearHistory: true });
                            return false;
                        }
                    );
            } else {
                this.router.navigateByUrl('/login', { clearHistory: true });
                return false;
            }
        } else {
            return true;
        }
    }

    canActivateChild(
        next: ActivatedRouteSnapshot,
        state: RouterStateSnapshot
    ): Observable<boolean> | Promise<boolean> | boolean {
        if (!this.authService.isLoggedIn) {
            if (this.authService.hasValidCredentials) {
                return this.authService
                    .renewCredentials()
                    .then(
                        () => true,
                        (error) => {
                            this.router.navigateByUrl('/login', { clearHistory: true });
                            return false;
                        }
                    );
            } else {
                this.router.navigateByUrl('/login', { clearHistory: true });
                return false;
            }
        } else {
            return true;
        }
    }
}
```

</details>

**Comment by kriefsacha** [comment]
Do you have a demo / an exemple , for me to be sure how it works  @charsleysa ?

Thank

**Comment by charsleysa** [comment]
@kriefsacha sorry I don't have an example as that code was pulled from an app we currently have in pre-release testing.

**Comment by kriefsacha** [comment]
I changed the scheme in the Manifest , in the setting of the auth0 , in the gradle , changed also the https in the callback urls to the app id.

Also added the library you told me , but now i have a blank browser page ..

If you don't have something that works with nativescript and smartphone we will just begin to search another auth provider i think ..

**Comment by charsleysa** [comment]
@kriefsacha if you want a simple demo of how this library works you can git clone this repo and run it. It is a verified working demo. The demo is written in NativeScript Core and there currently is no demo written in NativeScript angular.

**Comment by charsleysa** [comment]
Closing as original issue topic has been resolved.

**Comment by adrianeguez** [comment]
> Okay no problem we will use it like that,
> 
> So now i puted the last version of the library , my androidManifest is like that :
> 
> ```
> <?xml version="1.0" encoding="utf-8"?>
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
> 	package="__PACKAGE__"
> 	xmlns:tools="http://schemas.android.com/tools"
> 	android:versionCode="10000"
> 	android:versionName="1.0">
> 
> 	<supports-screens
> 		android:smallScreens="true"
> 		android:normalScreens="true"
> 		android:largeScreens="true"
> 		android:xlargeScreens="true"/>
> 
> 	<uses-sdk
> 		android:minSdkVersion="17"
> 		android:targetSdkVersion="__APILEVEL__"/>
> 
> 	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
> 	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
> 	<uses-permission android:name="android.permission.INTERNET"/>
> 
> 	<application
> 		android:name="com.tns.NativeScriptApplication"
> 		android:allowBackup="true"
> 		android:icon="@drawable/icon"
> 		android:label="@string/app_name"
> 		android:theme="@style/AppTheme">
> 
> 		<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
> 		
> 		<activity
> 			android:name="com.tns.NativeScriptActivity"
> 			android:label="@string/title_activity_kimera"
> 			android:configChanges="keyboardHidden|orientation|screenSize"
> 			android:theme="@style/LaunchScreenTheme"
> 			android:screenOrientation="portrait">
> 
> 			<meta-data android:name="SET_THEME_ON_LAUNCH" android:resource="@style/AppTheme" />
> 
> 			<intent-filter>
> 				<action android:name="android.intent.action.MAIN" />
> 				<category android:name="android.intent.category.LAUNCHER" />
> 			</intent-filter>
> 		</activity>
> 		<activity android:name="com.tns.ErrorReportActivity"/>
> 
>       <activity
>           android:name="org.nativescript.auth0.RedirectActivity"
>             tools:node="replace">
>           <intent-filter>
>               <action android:name="android.intent.action.VIEW" />
> 
>               <category android:name="android.intent.category.DEFAULT" />
>               <category android:name="android.intent.category.BROWSABLE" />
> 
>               <data
>                   android:host="jarggon.eu.auth0.com"
>                   android:pathPrefix="/android/org.nativescript.JarggonTranslatorApp/callback"
>                   android:scheme="https" />
>           </intent-filter>
>       </activity>
> 	  
> 	</application>
> </manifest>
> ```
> I have an Auth0Service like that
> 
> ```
> import { Injectable } from '@angular/core';
> import { Auth0 } from 'nativescript-auth0';
> 
> @Injectable()
> export class Auth0Service {
> 
>   public lock: any
>   constructor() {
>     this.lock = new Auth0('vHfWU8tWDEGTFosuqL9QnGG1RfsFh0T6', 'jarggon.eu.auth0.com');
>   }
> 
> }
> ```
> And in my home component i have :
> 
> ```
>     init() {
>         this.auth0Service.lock.webAuthentication({ scope: "openid offline_access" }).then( (auth0res)=> {
>             console.log('logged');
>         }, (error) =>{
>             console.log('lock error ' + error);
>         });
>     }
> ```
> I have the right callback url in auth0 and added the password grant type.
> 
> But on my screen i see :
> 
> > Cannot GET /android/org.nativescript.JarggonTranslatorApp/callback
> 
> And on the logs of auth0 i see Sucess Login everytime i try .. Maybe you have an idea ?

@kriefsacha  I have the same problem, if you hit the button to open in the browser, it gives you the option to open in chrome, other browsers AND your application. 

This issue is related to the kind of intent that is send from the library, I have not make it work normally but a workaround is that you hit the menu button, open in a browser and select your application so that the intent can open your application.

![image](https://user-images.githubusercontent.com/5687655/52386467-41bc7500-2a54-11e9-9c36-564b3ce557f3.png)

![image](https://user-images.githubusercontent.com/5687655/52386484-50a32780-2a54-11e9-8ea5-52e0ecefb416.png)

**Comment by davidpodhola** [comment]
Thanks @adrianeguez, works for me too. Adding `console.log`s to `redirectActivity.js` it really seems the secure browser does NOT fire the `org.nativescript.auth0.RedirectActivity` specified in `AndroidManifest.xml` unless you "Open in browser" and select your application. You can retrieve the tokens then.

I am not sure @charsleysa if this is because of some recent changes in how the secure browser instance works; I assume I have everything set up correctly if I get the token at the end.

**Comment by mm-spiio** [comment]
Can someone tell me what value should be specified for  'AUTH0_CREDENTIALS'?
