### ISSUE TITLE
[Vue] Error: com.tns.NativeScriptException: Failed to find module: "nativescript-auth0/auth0-common", relative to: app/tns_modules/

### ISSUE THREAD

**Issue by RyanDawkins** [sitefinitysteve/nativescript-auth0#36]
### Which platform(s) does your issue occur on?
- Android 
- iOS/Android versions Android 26
- emulator or device. What type of device? Nexus 6

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it): 4.2.3
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project): 4.2.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)  n/a
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
```json
"dependencies": {
    "nativescript-theme-core": "^1.0.4",
    "nativescript-vue": "^1.3.1",
    "tns-core-modules": "4.2.0",
    "vue-router": "^3.0.1",
    "nativescript-auth0": "2.0.3",
    "auth0-js": "^9.4.1",
    "nativescript-vue-externals": "0.2.0"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^3.0.2",
    "fs-extra": "^5.0.0",
    "nativescript-vue-externals": "^0.2.0",
    "nativescript-vue-loader": "^0.1.5",
    "nativescript-vue-target": "^0.1.0",
    "nativescript-vue-template-compiler": "^1.3.1",
    "node-sass": "^4.7.2",
    "ns-vue-loader": "^0.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.7",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.11.0",
    "webpack-synchronizable-shell-plugin": "0.0.7",
    "winston-color": "^1.0.0"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
I'm trying to use the default nativescript-vue template. After installing nativescript-auth0 with a clean vue template and following the directions from the README, I run into this error when running: `npm run watch:android`

### Is there any code involved?
``` ts
// main.ts
import authService from './services/auth.service';
(new authService()).login();
```

```js
// auth.service.js
export default class AuthService {

    constructor() {
        this.login = this.login.bind(this);
        this.auth0 = new auth0(clientId, domain);
    }

    login() {
        this.auth0.webAuthentication({
            scope: 'openid offline_access'
        }).then((res) => {
            console.log('res', res);
        }, (error) => {
            console.log('error', error);
        });
    }
}
```

**Comment by charsleysa** [comment]
Hi @RyanDawkins 
I have never used Vue before and don't know how it works under-the-hood so I won't be much help.
It looks like the files may be missed during compilation by the nativescript-vue plugin, try taking a look at the resulting files and see if there's anything missing.
Usually these files can be found in the platforms folder, try the following path:
`platforms/android/app/build/intermediates/assets/debug/app`

**Comment by charsleysa** [comment]
Hi @RyanDawkins 

There is now a working Vue demo using `nativescript-vue@2.0.0` so I will be closing this issue.
