### ISSUE TITLE
SafariSession is used instead of SafariAuthenticationSession in iOS 11.2.2

### ISSUE THREAD

**Issue by ssedlmaier** [sitefinitysteve/nativescript-auth0#37]
The test if iOS 11 is available in SafariWebAuth silently fails if the iOS version received by device.osVersion contains a patch level.

`Number(device.osVersion) >= 11.0 && this.authenticationSession`

e.g. Number('11.2.2') results in NaN. Therefore the conditions evaluates to false and the legacy authentication is used.

**Comment by charsleysa** [comment]
@ssedlmaier v2.0.4 has been released with the fix, thanks to @y-spreen for providing to fix!
