### ISSUE TITLE
How to pass Other AuthLock options???

### ISSUE THREAD

**Issue by oexza** [sitefinitysteve/nativescript-auth0#4]
How does one pass other options into AuthLock instance? i want to use a custom unique scheme and not https, but there seems not to be a way to do that.

**Comment by sitefinitysteve** [comment]
Sure, you mean like the builder right?
https://auth0.com/docs/libraries/lock-android/configuration

What if I allow you to pass in a builder object though .show?  The problem there is it would need to be done for each platform.

Option 2 is to wrap all the builder functions as "Options" on the Auth0Lock object (which I like a lot more)

**Comment by oexza** [comment]
Ahh yeah that makes sense and would be great.

**Comment by alexgtn** [comment]
@sitefinitysteve The question might be stupid but...)) I'm making changes to the auth0.android.ts file and then run the app inside /demo, but the changes don't reflect. I'm trying to customize the builder. What I'm doing wrong?

**Comment by vtjon** [comment]
Any updates on this? I need to modify the scheme because when the callback returns to my android app, I get the "Open With" box that has Classic Lock and Browser. I'm not sure if the same issue exists on iOS.

**Comment by sitefinitysteve** [comment]
That's just on android, working on it now, I'll let you know

**Comment by vtjon** [comment]
I am still researching this. It might be a configuration on my side as I might be able to bypass it without a custom scheme. I think I need to setup my package name at Auth0 and put the autoVerify attribute in the manifest file. I am not sure how this works prior to Android 6 though.

There are still some other options in the builder that are useful though.

**Comment by sitefinitysteve** [comment]
Yeah it DEFIANTLY needs to happen, I just didn’t *need* it initially so it wasn’t critical to get it up and going

**Comment by oexza** [comment]
Ping! bro any traction on this?

**Comment by sitefinitysteve** [comment]
No man, Auth0 doesn't seem to give a shit about the project so I've just
moved off... I don't have the time to enhance if they aren't gonna at least
work with us a bit.

It's a DRAIN to keep needing to refactor the entire thing everytime they
decide to rebuild their libs, and now with the swift implementation they
are refusing to expose the ObjC bridge for us...

PRs accepted clearly..

**Comment by charsleysa** [comment]
@oexza @vtjon 
Starting with version 2.0.0 this library has been rewritten to use Auth0 Universal Login and support for previous versions will be dropped.
