### ISSUE TITLE
Redirect to the app after email verification

### ISSUE THREAD

**Issue by niconaso** [sitefinitysteve/nativescript-auth0#42]
Is there any way to configure the "Redirect to" url (https://manage.auth0.com/#/emails) in the app? 
I need to redirect to an app after the user verifies his/her email. I tried using the same callback url I use to authorize the user, but the app opens it doesn't receives any params.
Thanks!

**Comment by charsleysa** [comment]
@niconaso one possible strategy is to have your app handle links for your website and check to see if the link is the email callback, if so then the app can handle it, if not then let it open in the web browser.

**Comment by niconaso** [comment]
Thanks!!
