### ISSUE TITLE
`Lock (~> 2.0)` required by `Podfile`

### ISSUE THREAD

**Issue by chrisjbrown** [sitefinitysteve/nativescript-auth0#5]
Error after installing and updating plist files

`tns run ios
Executing before-prepare hook from /Users/deBijenkorf/Apps/whattodo/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.1.6
Preparing project...
Successfully prepared plugin nativescript-angular for ios.
Successfully prepared plugin nativescript-intl for ios.
Successfully prepared plugin nativescript-auth0 for ios.
Successfully prepared plugin nativescript-iqkeyboardmanager for ios.
Successfully prepared plugin nativescript-social-share for ios.
Successfully prepared plugin nativescript-unit-test-runner for ios.
Successfully prepared plugin tns-core-modules for ios.
Successfully prepared plugin tns-core-modules-widgets for ios.
Installing pods...
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Lock (~> 2.0)` required by `Podfile`

Specs satisfying the `Lock (~> 2.0)` dependency were found, but they required a higher minimum deployment target.
Processing node_modules failed. Error: Command pod failed with exit code 1
Sending exception report (press Ctrl+C to stop).....`

**Comment by chrishawn** [comment]
I had this same issue, I had to fix it by Updating the XCode Project File to be "iOS Deployment Target" "9.0" or higher
