### ISSUE TITLE
Vue - Android - application.activity.foregroundActivity undefined

### ISSUE THREAD

**Issue by jawa-the-hutt** [sitefinitysteve/nativescript-auth0#52]
I'm getting this issue in a larger project I'm working in as well as the fork of this project I just created to validate if it was me or potentially the plugin.  I'm using NS-Vue.  I'm not sure if this is a NS-Vue specific issue or not, but I do have a suggested fix, which I'll show later. 

As I mentioned, I [forked](https://github.com/jawa-the-hutt/nativescript-auth0) this repo and have added a couple of views and moved some code around to try and simulate exactly what I'm seeing.   As an aside and maybe this is a different issue, I couldn't get the demo-vue to run and bundle if the plugin was being referenced in `src`.  I had to install the plugin from npm to get it to run correctly.

Inside of `main.ts` I'm attempting to intercept the logged in status of the user as the Vue instance is being setup.  this will force to user to the Login screen if they aren't logged in.

```
import Vue from 'nativescript-vue';
import App from './components/App.vue';
import Login from './components/Login.vue';

const isLoggedIn = true;

new Vue({
  render: (h) => h('frame', [h(isLoggedIn ? App : Login)]),
}).$start();
```

If I change `isLoggedIn` to false, then the Login page will show, but the Universal Login will not open up. and I get the following error in the console:
```
Successfully synced application org.nativescript.auth0demo on device emulator-5554.
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(NativeFrame)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(NativePage)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(NativeActionBar)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativepage), ElementNode(nativeactionbar))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(nativestacklayout)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> CreateElement(nativelabel)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativelabel))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativepage), ElementNode(nativestacklayout))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.2)} -> AppendChild(ElementNode(nativeframe), ElementNode(nativepage))'
JS: [TypeError: Cannot read property 'getPackageManager' of undefined] 'TypeError: Cannot read property \'getPackageManager\' of undefined
JS:     at WebAuthProvider.start (file:///data/data/org.nativescript.auth0demo/files/app/vendor.js:25220:58)
JS:     at file:///data/data/org.nativescript.auth0demo/files/app/vendor.js:25996:17
JS:     at new Promise (<anonymous>)
JS:     at Auth0.webAuthentication (file:///data/data/org.nativescript.auth0demo/files/app/vendor.js:25994:12)
JS:     at VueComponent.created (file:///data/data/org.nativescript.auth0demo/files/app/bundle.js:299:15)
JS:     at callHook (file:///data/data/org.nativescript.auth0demo/files/app/vendor.js:31906:21)
JS:     at VueComponent.Vue._init (file:///data/data/org.nativescript.auth0demo/files/app/vendor.js:39544:5)
JS:     at new VueComponent (file:///data/data/org.nativescript.auth0demo/files/app/vendor.js:39719:12)
JS:     at createComponentInstanceForVnode (file:///data/data/org.nativescript.auth0demo/files/app/vendor.js:39239:10)
JS:     at init (file:///data/data/org.nativescript.a...
```

In tracing down where the error is coming from, The exception is being thrown from [here](https://github.com/sitefinitysteve/nativescript-auth0/blob/2cc72d451b668693c40f76e47398c91e52f94d0b/src/android/provider/webAuthProvider.ts#L221), but it's really generated further upstream from [here](https://github.com/sitefinitysteve/nativescript-auth0/blob/2cc72d451b668693c40f76e47398c91e52f94d0b/src/auth0.android.ts#L67)

For whatever reason, at this point in the lifecycle, `application.activity.foregroundActivity` is undefined.  There is some discussion [here](https://github.com/NativeScript/NativeScript/issues/5307) about this, but I'm not knowledgeable enough to know if it's relevant or not.

However, I do know that if I change `foregroundActivity` to `startActivity`, then things work just fine without any issues.

### Which platform(s) does your issue occur on?
- Android, but I haven't tested this out on IOS and based on the suggested fix it may not be relevant to IOS.
- Android versions API 27 & 28
- emulator or device: this is on the android emulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.2.2
- Cross-platform modules: 5.1.2
- Runtime(s): 5.0.0 for both
- Plugin(s): 
```
"dependencies": {
    "@vue/devtools": "5.0.0-beta.3",
    "nativescript-auth0": "^2.1.0",
    "nativescript-socket.io": "^0.9.0",
    "nativescript-toast": "^1.4.6",
    "nativescript-vue": "^2.0.0",
    "nativescript-vue-devtools": "^1.0.0",
    "tns-core-modules": "^5.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "next",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "tns-platform-declarations": "^5.1.2",
    "typescript": "^3.2.4",
    "vue": "^2.5.22",
    "vue-loader": "^15.2.6",
    "webpack": "^4.16.4",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.1.0"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 
Check my [fork](https://github.com/jawa-the-hutt/nativescript-auth0) and run the demo-vue project.  You can leave the `isLoggedIn` variable to true for the first run just to validate you can navigate to the `About` view as well as manually navigate to the `Login` vue and have the Universal Login show up.

Once you change `isLoggedIn` to false and save, then on the reload it will try and redirect to `Login.vue` and will successfully do so, but the Universal Login will never appear.

**Comment by charsleysa** [comment]
Hi @jawa-the-hutt 

I took a quick look at your findings. My Vue understanding isn't great but it looks like you've placed the call to the Auth0 Login in the `created()` lifecycle hook and I think the `foregroundActivity` isn't available during that hook.

I think the `foregroundActivity` is available in the `mounted()` lifecycle hook. 

Discussion needs to be had to figure out if it's appropriate to change the use from `foregroundActivity` to `startActivity` or whether it's more of a documentation issue regarding which lifecycle events to use.

**Comment by jawa-the-hutt** [comment]
Hey...thanks for getting back so quick on the weekend.

I just updated to using the `mounted` life-cycle and the issue still occurs.  I've pushed the commit to the fork in the event you haven't tried it out yet.

**Comment by charsleysa** [comment]
Hi @jawa-the-hutt

Looks like the solution will need to be using both `foregroundActivity` and `startActivity`.

I think it's best to check to see if `foregroundActivity` is valid with `startActivity` as a fallback.

If you'd like to make the changes and submit a PR, I should be able to merge and publish tomorrow afternoon sometime.

**Comment by jawa-the-hutt** [comment]
Sure.  Do you want me to keep the changes I made to the Vue demo as part of the PR or undo those and just make the changes to the `foregroundActivity` logic?

**Comment by charsleysa** [comment]
Just the changes to the `foregroundActivity` logic so we keep the changes as small as possible (and also keep all the demos consistent).

**Comment by jawa-the-hutt** [comment]
and here's what I'm basically going to suggest with the PR:
```
return new Promise((resolve, reject) => {
            try {
                const activity = application.android.foregroundActivity === undefined ? application.android.startActivity : application.android.foregroundActivity;
                webAuth.start(activity, {
                    onFailure: (dialogOrException: android.app.Dialog | AuthenticationException) => {
                        if (dialogOrException instanceof android.app.Dialog) {
                            reject(new WebAuthException(dialogOrException.toString()));
                        } else {
                            reject(new WebAuthException(dialogOrException.getDescription()));
                        }
                    },
                    onSuccess: (credentials: Credentials) => {
                        resolve(credentials);
                    }
                });
            } catch (e) {
                reject(e);
            }
        });
```

**Comment by charsleysa** [comment]
Only change I would make is this line
`application.android.foregroundActivity === undefined`
to
`application.android.foregroundActivity == null`

That'll check for both undefined and null (which are both invalid in this case).
