### ISSUE TITLE
Browser not opening on Android (Xiaomi)

### ISSUE THREAD

**Issue by Nevaan** [sitefinitysteve/nativescript-auth0#56]
Hi,

I found the issue for the plugin, which appears only when running application with plugin on real device. Application starts, but browser with auth0 is not opening, it freezes app and after a longer time it returns WebAuthException. It works perfectly for iOS.

I was not able to see any logs or errors, but maybe its because I dont know how to retrieve it. 

### Which platform(s) does your issue occur on?
- Android
-Android version: Oreo
- device: Xiaomi Redmi 6

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.3.0
- Cross-platform modules: 5.4.2
- Runtime(s): 5.3.1
- Plugin(s): 2.1.1

### Please, tell us how to recreate the issue in as much detail as possible. 
This is reproducible for demo application present in repository (nativescript-core), when running on physical device (works well on simulator)   

### Is there any code involved? 
Demo application from repository

**Comment by charsleysa** [comment]
Hi @Nevaan 

You mentioned that you received a WebAuthException, could you please post details from the exception? 

Also, does the physical device you are using (Xiaomi Redmi 6) have Google Chrome browser installed? The plugin relies on Chrome Tabs API which may not work across every browser.

**Comment by Nevaan** [comment]
Hi

I think I was wrong about WebAuthException... It throws error on minimizing the window and reopening it, probably not related to the issue. But I used

`
tns device log
`

and I was able to retrieve some application(?) logs - basing on application PID which I gathered with 
`
adb shell ps
`
On Xiaomi it looks like [this](https://gist.github.com/Nevaan/7ec381912b5eea6fc705e320cc850eb9)

I guess that line
`
06-24 13:43:53.536 25144 25144 V CustomTabsController: Bind request result: false
`
can be crucial here. After this (I mean, after calling webAuthentication method), app just freezes.
 
Oh, and on all xiaomi devices I tested this on Chrome browser was present. What I noticed on one of them, is that there was also Mi Browser or something like this, too.

P.S. I plugged in other device - Sony on Android Marshmallow and it seems that plugin works good.

**Comment by charsleysa** [comment]
Hi @Nevaan 

Unfortunately I don't have that device and I am unable to recreate the issue. 

If you would like to investigate the issue I would recommend looking at the following code function as this is where something is most likely failing:
https://github.com/sitefinitysteve/nativescript-auth0/blob/e493d2cc94066c6a567aad699657adaf89737f83/src/android/provider/customTabsController.ts#L153

My thinking is that the custom tabs controller is failing to find a suitable browser, possibly due to missing Google services on the device. As I don't know much about the specific device I am unable to provide more insight.

**Comment by Nevaan** [comment]
Yeah, this is quite specific issue :( 

Ok, I've ran plugin demo on device and exactly, `customTabsBrowsers` array is empty so method you are talking about returns null.

So far I did not find any similar problems for Xiaomi on stack or wherever else, but I will try to find solution. Also, my proposal is to stop the process of authentication in this case (throw an exception?)

**Comment by Nevaan** [comment]
Hi @charsleysa 

Please correct me if I am wrong, but can't we just use default browser if no browser supporting custom tabs is present? In my case, `resolvedActivityList` contains "com.android.browser" package, and it seems to work if I return this value in line 189 in customTabsController.ts (properly opens auth0 in browser - btw. the one I mentioned, mi browser).

It is quite strange, but for some reason `pm.resolveService(serviceIntent, 0)` is not returning Chrome browser present on device (I've checked, Custom Tabs are in Chrome since version 45, while in my case there is version 75 installed)

If you agree (or if in the meantime I will find another solution) I can prepare PR. I just need this feature urgently (yep, typically), so I would be glad if we resolve this ASAP :)

**Comment by Nevaan** [comment]
Hi again,

After further investigation, I've found that that this line

https://github.com/sitefinitysteve/nativescript-auth0/blob/e493d2cc94066c6a567aad699657adaf89737f83/src/android/provider/customTabsController.ts#L165

returns only default browser (`com.android.browser`). Replacing the 0 value with 0x00020000 (MATCH_ALL) as in

https://github.com/sitefinitysteve/nativescript-auth0/blob/e493d2cc94066c6a567aad699657adaf89737f83/src/android/provider/customTabsController.ts#L156-L159

makes `resolvedActivityList` contain all browsers (mi browser + chrome, which is expected) and continue with success. Maybe this is better solution?

**Comment by charsleysa** [comment]
Hi @Nevaan 

Thanks for investigating the issue! 
I agree with your latest proposed changes. 

If that change allows your device to work and doesn't break existing devices then I'll happily accept a PR.
