### ISSUE TITLE
GetUserInfo returns undefined but its properties are defined

### ISSUE THREAD

**Issue by dennisheer** [sitefinitysteve/nativescript-auth0#59]
After initializing the `auth0` object as described in the docs and successfully completing `webAuthentication`, the method `getUserInfo` returns an undefined `UserInfo` object. Some properties of this (allegedly) undefined `UserInfo` are *not* undefined and accessible by property accessors dot (`userInfo.sub`) or bracket (`userInfo['sub'])` notation. Despite properties of the object being accessible, the object is interpreted as being undefined during runtime.

I tried:
* Using the `promise.then` and the ES6 `await` syntax
* Initializing the returned `UserInfo` object with the `UserInfo.initWithJson` method
* Creating a new `UserInfo` object and adding the keys manually

*How can a JavaScript object be undefined although some of its properties are defined?*

See code example for more context.

### Platforms
* iOS 12.4 on an iPhone 6 simulator
* iOS 12.4 on an iPhone SE

### Version numbers
- CLI: 6.0.1
- Cross-platform modules: 6.0.1
- Runtime(s): 6.0.1
<details><summary>Plugin(s):</summary>

```
  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "kinvey-nativescript-sdk": "4.2.1",
    "nativescript-angular": "^8.0.2",
    "nativescript-auth0": "^2.1.2",
    "nativescript-barcodescanner": "^3.2.1",
    "nativescript-local-notifications": "^4.0.0",
    "nativescript-plugin-firebase": "^9.0.3",
    "nativescript-secure-storage": "^2.5.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.3.3",
    "subsink": "^1.0.0",
    "tns-core-modules": "6.0.1",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.0.0",
    "@ngtools/webpack": "~8.0.0",
    "nativescript-dev-webpack": "1.0.1",
    "tns-platform-declarations": "6.0.1",
    "node-sass": "4.12.0",
    "typescript": "~3.4.5"
  }
```

</details>

### Steps to reproduce
1. Initialize `auth0`
2. Authenticate using `this.auth0.webAuthentication(…)` and save the `credentials`
3. Use `this.credentials.accessToken` to `getUserInfo` and save the `userInfo`
4. Try using `this.userInfo` e.g. by printing to console `console.log(this.userInfo)`

### Workaround
Iterating over the keys of the returned user info and constructing a new element with its values where applicable:

```
      const accessToken = await this.getAccessToken();
      const userInfoRaw = await this.auth0.getUserInfo(accessToken); // this returns undefined although some object properties are accessible
      const userInfo = <UserInfo>{};

      for (const key in userInfoRaw) {
        if (userInfoRaw.hasOwnProperty(key)) {
          userInfo[key] = userInfoRaw[key];
        }
      }
```

### Code example
https://play.nativescript.org/?template=play-ng&id=y1V4WU&v=3

**Comment by charsleysa** [comment]
Hi @dennisheer 

Thanks for reporting this.

Long story short, `UserInfo` class uses the common interface `.toJSON()`. There was a bug in this function where the return statement was missing so the function resulted in `undefined`.
`console.log()` seems to use this `.toJSON()` interface so it was showing undefined even though there was a real (and valid) value.

This issue has been fixed in v3.0.1
