### ISSUE TITLE
Data loss when persisting a wrapped UserInfo 

### ISSUE THREAD

**Issue by dennisheer** [sitefinitysteve/nativescript-auth0#60]
When persisting an `UserInfo` object wrapped inside a different object to local or secure storage, the following keys are not being read back correctly from storage:

```
var profileURL = json["profile"];
var pictureURL = json["picture"];
var websiteURL = json["website"];
```

The wrapper object might look like this:
```
{
    id: string,
    userInfo: UserInfo
}
```

The wrapper object is being transformed to JSON by calling `JSON.stringify()`. Therefore the `userInfo` object is not being transformed by using `toJSON`. This means the three properties as seen above are not being transformed from JWT standard names `profile`, `picture` and `website` to the `nativescript-auth0` names `profileURL`, `pictureURL`, `websiteURL` and vice versa. The data is being lost on reading from storage and writing to storage again.

*How to persist `UserInfo` to storage inside a wrapper object without data loss and without saving `UserInfo` on its own?*

### Platforms
* iOS 12.4 on an iPhone 6 simulator
* iOS 12.4 on an iPhone SE

### Version numbers
- CLI: 6.0.1
- Cross-platform modules: 6.0.1
- Runtime(s): 6.0.1
<details><summary>Plugin(s):</summary>

```
  "dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "kinvey-nativescript-sdk": "4.2.1",
    "nativescript-angular": "^8.0.2",
    "nativescript-auth0": "^2.1.2",
    "nativescript-barcodescanner": "^3.2.1",
    "nativescript-local-notifications": "^4.0.0",
    "nativescript-plugin-firebase": "^9.0.3",
    "nativescript-secure-storage": "^2.5.0",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.3.3",
    "subsink": "^1.0.0",
    "tns-core-modules": "6.0.1",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.0.0",
    "@ngtools/webpack": "~8.0.0",
    "nativescript-dev-webpack": "1.0.1",
    "tns-platform-declarations": "6.0.1",
    "node-sass": "4.12.0",
    "typescript": "~3.4.5"
  }
```

</details>

### Steps to reproduce
1. Initialize `auth0`
2. Authenticate using `this.auth0.webAuthentication(…)` and save the credentials
3. Use `this.credentials.accessToken` to `getUserInfo` and save the `userInfo` wrapped inside of a different object
4. Persist the wrapper object by using `JSON.stringify()`
5. Read the wrapper object from storage by using `JSON.parse()`
6. Access any of the three properties and find they are undefined even though they weren't before persisting

**Comment by charsleysa** [comment]
Hi @dennisheer 

Since `UserInfo` is a class and not a plain javascript object, serialization and deserialization requires extra steps.

The `UserInfo` class implements the standard interface `.toJSON()` so when `JSON.stringify()` serializes a `UserInfo` object it looks different as the class outputs JSON using claim names from the OIDC specification.

In order to deserialize a `UserInfo` object properly you must pass the resulting javascript object from `JSON.parse()` to `UserInfo.initWithJson()` in order to receive a `UserInfo` object.

So with your particular example, your code could look something like:
```ts
// serialize
const myUserInfoObject = ...
const myWrapper = { id: 'some_id', userInfo: myUserInfoObject };
const json = JSON.stringify(myWrapper);

// deserialize
const pojo = JSON.parse(json);
const myNewWrapper = { id: pojo.id, userInfo: UserInfo.initWithJson(pojo.userInfo) };

// alternative deserialize
const myAlternativeWrapper = JSON.parse(json);
myAlternativeWrapper.userInfo = UserInfo.initWithJson(myAlternativeWrapper.userInfo);
```
