### ISSUE TITLE
webAuthentication redirect for Android API 23 and lower - Vue

### ISSUE THREAD

**Issue by ahmadsha7** [sitefinitysteve/nativescript-auth0#63]
## Which platform(s) does your issue occur on?
- Platform: Android
- Version: 6.0, Marshmellow, API 23
- Emulator: Samsung Galaxy A3 (2016)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.0
- Cross-platform modules: ^6.1.1
- Runtime(s): Both 6.1.1
- Plugin(s): 
```javascript
"dependencies": {
    "@vue/devtools": "^5.1.1",
    "axios": "^0.19.0",
    "nativescript-auth0": "^3.0.1",
    "nativescript-socketio": "^3.3.1",
    "nativescript-theme-core": "^2.0.21",
    "nativescript-toasty": "^1.4.0",
    "nativescript-vue": "^2.4.0",
    "nativescript-vue-devtools": "^1.2.0",
    "tns-core-modules": "^6.1.1",
    "vue-axios": "^2.1.4"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "babel-loader": "^8.0.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "^1.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "^1.2.0",
    "nativescript-vue-template-compiler": "^2.0.0",
    "nativescript-worker-loader": "~0.9.0",
    "node-sass": "^4.9.2",
    "sass-loader": "^7.1.0",
    "terser-webpack-plugin": "^1.1.0",
    "vue-loader": "^15.2.6",
    "webpack": "^4.16.4",
    "webpack-bundle-analyzer": "~2.13.1",
    "webpack-cli": "^3.1.0"
  }
```

### Please, tell us how to recreate the issue in as much detail as possible. 

I've correctly followed the configuration for the Android setup stipulated in your README file. 

I'm using **nativescript-vue** and the below code is part of an authentication class export.

**auth.service.js**
```javascript
  import { Auth0 } from 'nativescript-auth0';

  const CLIENTID = "imyourfavoriteclient"
  const DOMAIN = "whatislyf.com"

  export default class AuthService {
    isLoggedIn() {
      return ApplicationSettings.getBoolean('isLoggedIn', false);
    }

    login() {
      return new Auth0(CLIENTID, DOMAIN)
        .webAuthentication({
          scope: 'openid offline_access',
          parameters: {
            prompt: 'login'
          }
        })
       .then(x => console.log('LOG USER IN!'))
     }
  }
```

**main.js**
```javascript
import Vue from 'nativescript-vue';

import AuthService from './services/auth.service';

import App from './screens/App';
import Login from './screens/Login.vue';

const authService = new AuthService();

new Vue({
  render: h => h('frame', [h(authService.isLoggedIn() ? App : Login)])
}).$start();
```

The above code does not call a redirect for Android versions on 6.0 (Marshmellow) and lower on Android. Works perfectly fine on versions 7.0 (Nougat) and higher on Android by redirecting the user to google chrome for auth0 Login.

This is very problematic when I'm conducting a responsive design for old android versions and the app has auth0 as a bottleneck to enter the application. Please do reply asap because I'm nearing the publication date for my app at the Google Play Store.

**Comment by charsleysa** [comment]
Hi @ahmadshahrour951 

Do you receive any errors when debugging the app? 

Do you see the Auth0 login screen at all on the Android 6.0 device?

**Comment by ahmadsha7** [comment]
@charsleysa Thank you for the quick reply! I don't get any console logs when in debugging mode, I assume it fails silently.

I **_do not_** see any Auth0 login screen at all when in version 6.0 or below, which is why I'm putting up this issue.

For versions 7.0 and above, the Auth0 login screen pops up perfectly fine.

**Comment by charsleysa** [comment]
Hi @ahmadshahrour951 

Thanks for the information, I have confirmed it's a bug and will be releasing a fix.
