### ISSUE TITLE
NS Vue Successful Login But Get Safari Cannot Open The Page

### ISSUE THREAD

**Issue by AngeloAnolin** [sitefinitysteve/nativescript-auth0#64]
### Make sure to check the demo app(s) for sample usage 
App is copied from Demo Vue branch.

### Make sure to check the existing issues in this repository 
Was not able to find a similar issue.

### If the demo apps cannot help and there is no issue for your problem, tell us about it
I followed the Vue Demo branch. In my application, I am able to invoke the Auth0 login via the following code:

```
login () {
  const auth0 = new Auth0('CLIENT_ID', 'DOMAIN');
  auth0.webAuthentication({
    scope: "openid offline_access"
  }).then((result) => {
    console.log('result', result)
  })
}
```

When the Auth0 window opens, I enter valid credentials and proceeded. Afterwards, Safari just displays:

**Safari cannot open the page because the address is invalid.**

I check the logs on my Auth0 and it says Successful Login.

### Which platform(s) does your issue occur on?
- iOS Emulator (iPhone 8) and actual iPhone Device

### Please, provide the following version numbers that your issue occurs with:
- TNS Version 6.0.2
- TNS iOS version 6.0.1
- "nativescript-auth0": "^3.0.1",

### Please, tell us how to recreate the issue in as much detail as possible. 
Followed steps as provided in the demo and notes. 

### Is there any code involved? 
Sample code to invoke the login page is provided above.

**Comment by charsleysa** [comment]
Hi @AngeloAnolin 

Just to double check, have you made sure to add the [necessary configuration](https://github.com/sitefinitysteve/nativescript-auth0#ios) to your `Info.plist` file? (Remembering to replace `YOUR_APP_BUNDLE_IDENTIFIER` with your app's bundle identifier as it *does not* get automatically replaced)

**Comment by AngeloAnolin** [comment]
Update: Got things working. 

The issue was related to the info.plist entries for the app. You need to make sure that the XML is well-formed (proper spacing, indentation etc) as well as the correct entries are made (On my part, I never had to change the values I have placed).

After entering the plist values, I performed the following to clean up and rebuild my app
`rm -rf platforms/*`
Then proceeded to rebuild my app and run it.
