### ISSUE TITLE
Tokens Used for API Call Getting Unauthorized

### ISSUE THREAD

**Issue by AngeloAnolin** [sitefinitysteve/nativescript-auth0#65]
### Question
My authentication workflow is working as described in the example. After successful login, I get the following information:

```
{
  "access_token":"*************************",
  "token_type":"Bearer",
  "id_token":"***************************************",
  "refresh_token":"**************************************",
  "expires_in":86400,
  "expires_at":"2019-10-18T23:04:50.387Z"
}

```
As I am also using Auth0 to secure my backend services, I tried to pass the tokens I retrieved (access_token, id_token) but both of them are getting an unauthorized response from my backend.

Is there an additional step that I need to take to get the proper access token that I can use as Bearer authorization on my api call?

My code so far (NS-Vue):

```
login () {
  let auth0 = new Auth0('*****', '*****.auth0.com')
  auth0.webAuthentication({
    scope: 'openid offline_access'
  }).then((result) => {
    let authenticationCredentials = result
    let access_token = authenticationCredentials.access_token
    let id_token = authenticationCredentials.id_token

    // Using any token to an Auth0 Protected Backend API call is saying not authorized....
    auth0.getUserInfo(access_token).then((userInfo) => {
      // userInfo object is retrieved here properly...
      console.log(JSON.stringify(userInfo))
    })
  })
}
```

### Which platform(s) does your issue occur on?
- iOS
- emulator or device. (Both)

### Additional Info
The access_tokens retrieved allows me to:
- get the user info properly.
- Using the jwt.io validator, I am able to validate the id_token retrieved from the authentication flow. But the access_token is not valid.
- Do I need to pass in an audience value in the Auth0 initialization?

**Comment by charsleysa** [comment]
Hi @AngeloAnolin 

It looks like you're missing the `audience` parameter which needs to match the url of an API you have setup using the Auth0 Dashboard.

For more information take a look at [these docs](https://auth0.com/docs/flows/guides/auth-code-pkce/call-api-auth-code-pkce).
