### ISSUE TITLE
Odd iOS safari authenication interaction

### ISSUE THREAD

**Issue by krthush** [sitefinitysteve/nativescript-auth0#66]
### Which platform(s) does your issue occur on?

- iOS
- iOS 13.1.3
- iPhone 7

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Cross-platform modules: 6.1.1
 
package.json file:

![image](https://user-images.githubusercontent.com/33790334/67231046-73386d80-f436-11e9-8c1e-f6899b315d38.png)

### Please, tell us how to recreate the issue in as much detail as possible. 

I should start by saying that I've succesfully managed get this entire authenication flow working for Android without any problems.

Now when I attempt it on iOS the following steps occur:

- As soon as the app starts an authenication call is started (with a 'none' prompt), on first time load of the app. Now in this scenario it **should prompt the user for their credentials** since there is no stored token in safari, but instead it tries to authenicate and fails. It does open the browser but fails to authenicate... here are the Auth0 logs to confirm this:

![image](https://user-images.githubusercontent.com/33790334/67231497-518bb600-f437-11e9-91d1-c0c9ac016819.png)

- After this, I built the page such that there is a fail safe with an authenication call with a 'login' prompt. Now as expected, after the user clicks this it opens up a form for the user to fill in their credentials. After succesful authenication (Auth0 logs confirm the auth is succesful) (there also is a pop up that comes and vanishes really quick to save the password), then the authenication promise itself reports back as failing.

- Now if the user exits the app (clears the app from the tray), and reopens it, the entire authenication flow suceeds without needed the user to enter their credentials - confirming that safari did indeed succesfully log the user in... After this the remainder of the app works - but I require the authenication process to work in an intuitive manner.

Why is the authenication flow not going as expected? Am I missing something?

### Is there any code involved? 
My project is a nativescript-vue one, I'm attaching the main Master.vue component where the authenication takes place, as well as my main.js

Master.vue:

![image](https://user-images.githubusercontent.com/33790334/67232373-2904bb80-f439-11e9-904e-dadceb31cadf.png)

main.js:

![image](https://user-images.githubusercontent.com/33790334/67232433-4174d600-f439-11e9-9af9-99494fd02a2b.png)

**Comment by krthush** [comment]
Okay, sorry about this but the "second" part of the problem, i.e. the authenication failing when it hits my "prompt: login" failsafe, was my fault. This part of the code:

![image](https://user-images.githubusercontent.com/33790334/67238793-a5050080-f445-11e9-8689-4f3859c3b3f6.png)

was a silly mistake... fixed it to this:

![image](https://user-images.githubusercontent.com/33790334/67238837-b9e19400-f445-11e9-8b49-ee777b3ba555.png)

After this the iOS authenication flow works if the user hits the failsafe and clicks the login button, enters their credentials, then the app follows through as expected. This is acceptable although it would be better if the prompt was automatic i.e there is still the first issue... that is:

> As soon as the app starts an authenication call is started (with a 'none' prompt), on first time load of the app. Now in this scenario it should prompt the user for their credentials since there is no stored token in safari, but instead it tries to authenicate and fails. It does open the browser but fails to authenicate... here are the Auth0 logs to confirm this:

**Comment by charsleysa** [comment]
Hi @krthush 

When the prompt parameter is set to none, Auth0 will *never* show a UI for the user to login. You as a developer must manually handle the case when a login required error is returned.

**Comment by krthush** [comment]
Ah I see, so presumable I had the wrong process for Android as well... okay in that case if I am to do the handling of when logins must be performed, I'll piggy back off of secure storage and try something like this for now:

![image](https://user-images.githubusercontent.com/33790334/67244495-b6eca080-f451-11e9-8a3b-1ebfdd925cb9.png)

I'll eventually get round to storing refreshTokens and using that with secure storage as well to prevent user logins.

Thanks!
