### ISSUE TITLE
Could not install /Users/steve/Dropbox/Projects/Plugins/nativescript-auth0

### ISSUE THREAD

**Issue by datanotion** [sitefinitysteve/nativescript-auth0#8]
Just checking to make sure I'm not doing something wrong, but when trying to run the Demo app you provided I get this after running tns install:

Could not install /Users/steve/Dropbox/Projects/Plugins/nativescript-auth0

which shows in package.json line 12:

"nativescript-auth0": "file:///Users/steve/Dropbox/Projects/Plugins/nativescript-auth0",

changing that to:

"nativescript-auth0": "^1.0.1",

fixes the issue.

Thanks!

**Comment by bradmartin** [comment]
https://github.com/sitefinitysteve/nativescript-auth0/pull/10 fixes it - Not you @datanotion 👍
